name: Test with Maven

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  testBuild:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        java-version: [8, 11, 16]
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2
      - name: "Prepare Java ${{ matrix.java-version }}"
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "${{ matrix.java-version }}"
      - name: "Make build.gradle executable"
        run: "chmod +x gradlew"
      - name: "Build jar with Java ${{ matrix.java-version }}"
        run: "./gradlew shadowJar"
      - name: "Delete Artifacts"
        run: "rm -rf build/libs/*.jar"
