name: Test with Gradle

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  testBuild:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2
      - name: "Setup JDK"
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"
      # Validate Gradle Wrapper
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      # Make Gradle Executable
      - name: Make build.gradle executable
        run: chmod +x gradlew
      # Build with Gradle
      - name: Build jar with Java 11
        run: ./gradlew shadow
      # Delete The Artifacts
      - name: Delete Artifacts
        run: rm -rf build/libs/*.jar
